[global]
treatment_node = "fertilizerAmountP"
outcome_node = "outcome"
conditional_nodes = ["fertilizerTiming", "soil", "fieldHistory"]
random_seed = 43

[experiments.MainDML]
dag = "main-rev.json"
adjustment_set = "BACKDOOR_EFFICIENT"
estimators = ["DML_SOIL", "DML_SOIL_RATE_SPLINE", "DML_SOIL_TIME"]
#estimators = ["DML_SOIL_RATE_SPLINE"]
[experiments.MainDML.robustness]
#PlaceboTest = ["DML_SOIL", "DML_SOIL_TIME", "DML_SOIL_RATE_SPLINE"]
#PlaceboTest = ["DML_SOIL_RATE_SPLINE"]
#SensitivityAnalysis = ["DML_SOIL", "DML_SOIL_TIME"]
PreTreatmentPlacebo = ["DML_SOIL"]
#UnobservedCommonConfounder = ["DML_SOIL", "DML_SOIL_RATE_SPLINE"]

[experiments.MainOLS]
dag = "main-rev.json"
adjustment_set = "BACKDOOR_EFFICIENT"
estimators = ["OLS_SOIL", "OLS_SOIL_RATE_SPLINE", "OLS_SOIL_TIME"]
[experiments.MainOLS.robustness]
PlaceboTest = ["OLS_SOIL_RATE_SPLINE"]

[experiments.MainRF]
dag = "main-rev.json"
adjustment_set = "BACKDOOR_EFFICIENT"
estimators = ["RF_PREDICTIVE"]

[experiments.MainGPS]
dag = "main-rev.json"
adjustment_set = "BACKDOOR_EFFICIENT"
estimators = ["GPS_SOIL_RATE"]
[experiments.MainGPS.robustness]
PlaceboTest = ["GPS_SOIL_RATE"]

[experiments.ExahustiveAdjDML]
dag = "main-rev.json"
adjustment_set = "BACKDOOR_EXHAUSTIVE"
estimators = ["DML_SOIL", "DML_SOIL_RATE_SPLINE", "DML_SOIL_TIME"]

[experiments.NtoPDML]
dag = "n-to-p.json"
adjustment_set = "BACKDOOR_EFFICIENT"
estimators = ["DML_SOIL", "DML_SOIL_RATE_SPLINE", "DML_SOIL_TIME"]

[experiments.ExahustiveAdjOLS]
dag = "main-rev.json"
adjustment_set = "BACKDOOR_EXHAUSTIVE"
estimators = ["OLS_SOIL", "OLS_SOIL_RATE_SPLINE", "OLS_SOIL_TIME"]