import os
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

def plot_dose_response_curve(dose_resp_df, save_path=None, fertilizer='N', ax=None, label=None, plot_ci=True, color_mapping=None, plot_legend=True, **kwargs):
    """
    Plots the dose response curve from the DataFrame generated by estimate_dose_response.
    """
    try:
        plt.style.use('publication.mplstyle')
    except Exception as e:
        print(f"Warning: Could not load publication.mplstyle: {e}")
        
    plt.rcParams['axes.prop_cycle'] = mpl.cycler(
        'color', ('#E66100', '#5D3A9B', '#E1BE6A', '#40B0A6', '#1A85FF', '#D41159')
    )
    cycle_colors = [i['color'] for i in plt.rcParams['axes.prop_cycle']]
    
    if ax is None:
        fig, ax = plt.subplots(1, 1, figsize=(3, 2.5))
    else:
        fig = ax.figure
    
    if color_mapping is None:
        colors = {'Non-sandy': cycle_colors[0], 'Sandy': cycle_colors[1]}
    else:
        colors = color_mapping
        
    for soil_type in ['Non-sandy', 'Sandy']:
        if soil_type in dose_resp_df.index.get_level_values('Soil type'):
            df_soil = dose_resp_df.xs(soil_type, level='Soil type')
            
            if label == "_nolegend_":
                label_str = "_nolegend_"
            elif label is not None:
                label_str = label if soil_type == 'Non-sandy' else "_nolegend_"
            else:
                label_str = soil_type
                
            sns.lineplot(
                x=df_soil.index, y=df_soil['Mean Lift'], ax=ax,
                label=label_str, color=colors.get(soil_type, 'k'), zorder=4, **kwargs
            )
            if plot_ci:
                ax.fill_between(
                    x=df_soil.index, y1=df_soil['Lower CI'], 
                    y2=df_soil['Upper CI'], alpha=0.1, color=colors.get(soil_type, 'k'), linewidth=0, zorder=3
                )
            
    title_fertilizer = 'Nitrogen' if fertilizer == 'N' else 'Phosphorus'
    ax.set_title(title_fertilizer)
    ax.set_xlabel(f'{fertilizer}-rate (kg/ha)')
    ax.set_ylabel('Change in yield compared to using\nthe reference nutrient rate (kg/ha)')
    
    if plot_legend:
        ax.legend(loc='upper left', title='Soil Type', frameon=False)
        
    ax.grid(which='minor', linestyle=':')
    

    t_vals = dose_resp_df.index.get_level_values('T')
    ax.set_xlim(t_vals.min(), t_vals.max())
    
    if save_path is not None:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        fig.savefig(save_path, format='pdf', bbox_inches='tight', dpi=300)
        plt.close(fig)
    print(f"Saved dose response plot to {save_path}")

def plot_average_marginal_effect(ame_df, T_absolute, save_path=None, fertilizer='N', axes=None):
    import numpy as np
    try:
        plt.style.use('publication.mplstyle')
    except Exception as e:
        pass
        
    plt.rcParams['axes.prop_cycle'] = mpl.cycler(
        'color', ('#E66100', '#5D3A9B', '#E1BE6A', '#40B0A6', '#1A85FF', '#D41159')
    )
    cycle_colors = [i['color'] for i in plt.rcParams['axes.prop_cycle']]
    
    # We infer step_size from the dataframe index difference
    # Assumes uniform stepping
    t_vals = sorted(ame_df.index.get_level_values('T').unique())
    step_size = t_vals[1] - t_vals[0] if len(t_vals) > 1 else 10
    
    # x_ is the grid of evaluating edges
    x_ = np.array(t_vals + [t_vals[-1] + step_size])
    
    if axes is None:
        fig, axes = plt.subplots(2, 2, figsize=(5.5, 3), sharey=False, sharex=False, height_ratios=[5, 1])
    else:
        fig = axes[0][0].figure
    
    for n, soil in enumerate(('Non-sandy', 'Sandy')):
        ax = axes[0][n]
        ax2 = axes[1][n]
        
        ax.axhline(0, color='k', linestyle='--')
        
        if soil not in ame_df.index.get_level_values('Soil type'):
            continue
            
        df_soil = ame_df.xs(soil, level='Soil type')
        lift_inference = df_soil[['Mean Lift', 'Lower CI', 'Upper CI']].values
        
        for i, t in enumerate(x_[:-1]):
            t1 = x_[i+1]
            
            ax.fill_between(
                x=[x_[i], x_[i+1]], y1=lift_inference[i][1], y2=lift_inference[i][2],
                alpha=0.1, color=cycle_colors[n], linewidth=0, label='95% CI' if i==0 else None
            )

            # Histogram matching logic
            count = ((T_absolute >= t) & (T_absolute < t1)).sum()
            ax2.fill_between(
                x=[x_[i], x_[i+1]], y1=0, y2=count,
                alpha=.8, color=cycle_colors[n], linewidth=0, label='95% CI' if i==0 else None
            )
            
        ax.hlines(
            y=lift_inference[:, 0], xmin=x_[:-1], xmax=x_[1:], linewidth=2,
            label='Average', color=cycle_colors[n]
        )
        
        if n == 0: 
            ax.set_ylabel(f'Marginal effect\n(kg Grain/kg {fertilizer})')
            ax2.set_ylabel('Sample\ncount',)
            
        ax.set_xticks(x_[:])
        ax.grid(which='major', linestyle=':', axis='x')
        # Setting a consistent ylim might require looking at data bounds, 
        # but user's code forced ax.set_ylim(-17, 38). Let's use dynamic with margins.
        min_y = np.nanmin(lift_inference[:, 1]) - 5
        max_y = np.nanmax(lift_inference[:, 2]) + 5
        ax.set_ylim(min_y, max_y)
        ax.set_xlim(x_[0], x_[-1])
        
        title_fertilizer = 'nitrogen' if fertilizer == 'N' else 'phosphorus'
        ax.set_title(f'Marginal effect of {title_fertilizer},\n{soil} soils')
        
        ax.text(
            0, 1, ('a', 'b')[n], transform=ax.transAxes, va='center', ha='center', fontsize=8,
            fontweight='bold', bbox=dict(boxstyle='circle', fc='w', ec='k')
        )
        ax.set_xticks(ax.get_xticks(), minor=True)
        ax.set_xticks([], minor=False)
        ax.grid(which='minor', linestyle=':', axis='x')
        
        ax.legend(loc='upper right', frameon=False)
        
        # Histplot
        # Dynamic limit for histogram
        counts = [((T_absolute >= t) & (T_absolute < x_[i+1])).sum() for i, t in enumerate(x_[:-1])]
        max_count = max(counts) if counts else 100
        # Round up to nearest 10
        import math
        max_hist_y = math.ceil(max_count / 10.0) * 10
        
        ax2.set_ylim(0, max_hist_y)
        ax2.set_xticks(x_[:])
        ax2.set_xlim(x_[0], x_[-1])
        # ax2.set_yticks(np.arange(0, max_hist_y+1, max_hist_y//5 if max_hist_y > 0 else 10), minor=True)
        ax2.grid(which='major', linestyle=':', axis='x')
        
        ax2.set_xticklabels([f'{x_[i]:.0f}' for i, _ in enumerate(x_[:])], rotation=90)
        ax2.set_xlabel(f'Range of {fertilizer}-rate (kg/ha)')
        
    plt.tight_layout()
    plt.subplots_adjust(hspace=.05)
    
    if save_path is not None:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        fig.savefig(save_path, bbox_inches='tight', dpi=300)
        plt.close(fig)
    print(f"Saved average marginal effect plot to {save_path}")

def plot_point_estimates(causal_df, save_path=None, fertilizer='N', ax=None, xlim=None, label=None, plot_ci=True, color_mapping=None, **kwargs):
    import numpy as np
    try:
        plt.style.use('publication.mplstyle')
    except Exception as e:
        pass
        
    plt.rcParams['axes.prop_cycle'] = mpl.cycler(
        'color', ('#E66100', '#5D3A9B', '#E1BE6A', '#40B0A6', '#1A85FF', '#D41159')
    )
    cycle_colors = [i['color'] for i in plt.rcParams['axes.prop_cycle']]
    
    estimator_name = causal_df['Estimator'].iloc[0]
    
    # Parse parameter names into Soil and Group
    df = causal_df[causal_df['Parameter'].str.startswith('CATE: ')].copy()
    
    def parse_soil_and_group(param):
        p = param.replace('CATE: ', '')
        if 'Non-sandy' in p:
            soil = 'Non-sandy'
            group = p.replace('Non-sandy', '').replace('N_fertN_', '').replace('N_', '').strip('_')
        elif 'Sandy' in p:
            soil = 'Sandy'
            group = p.replace('Sandy', '').replace('N_fertN_', '').replace('N_', '').strip('_')
        else:
            soil = None
            group = p
        if group == '':
            group = 'Overall'
        return pd.Series([soil, group])
        
    df[['Soil type', 'Group']] = df['Parameter'].apply(parse_soil_and_group)
    df = df[df['Soil type'].notnull()]
    
    # Ignore the extra causal rate parameters (Opt T Range, etc.) if they sneaked in
    df = df[~df['Group'].str.contains('Opt T Range|Low Non-Retu|High Non-Ret|Low Non-|High Non', na=False)]
    
    if color_mapping is None:
        colors = {'Non-sandy': cycle_colors[0], 'Sandy': cycle_colors[1]}
    else:
        colors = color_mapping
        
    plot_kwargs = {'markersize': 4}
    if plot_ci:
        plot_kwargs['fmt'] = kwargs.pop('marker', 'o')
        plot_kwargs['linewidth'] = 2
    else:
        plot_kwargs['marker'] = kwargs.pop('marker', 'o')
        plot_kwargs['linestyle'] = 'none'
        
    plot_kwargs.update(kwargs)
    
    if ax is None:
        if 'TIME' in estimator_name:
            if fertilizer == 'N':
                fig, ax = plt.subplots(1, 1, figsize=(2.5, 2.0))
            else:
                fig, ax = plt.subplots(1, 1, figsize=(2.5, 1.1))
        elif 'LEGUME' in estimator_name:
            fig, ax = plt.subplots(1, 1, figsize=(2.5, 1.0))
        elif 'PFERT' in estimator_name:
            fig, ax = plt.subplots(1, 1, figsize=(2.5, 1.5))
        else:
            fig, ax = plt.subplots(1, 1, figsize=(2.5, 1.0))
    else:
        fig = ax.figure
        
    if 'TIME' in estimator_name:
        if fertilizer == 'N':
            xlim = (-24, 74) if xlim is None else xlim
            xlabel = 'Average N-AE (kg/kg)'
            title = 'Nitrogen'
        else:
            xlim = (-50, 120) if xlim is None else xlim
            xlabel = 'Average P-AE (kg/kg)'
            title = 'Phosphorus'
    elif 'LEGUME' in estimator_name:
        xlim = (-10, 55) if xlim is None else xlim
        xlabel = 'Average N-AE (kg/kg)'
        title = None
    elif 'PFERT' in estimator_name:
        xlim = (-10, 40) if xlim is None else xlim
        xlabel = 'Average N-AE (kg/kg)'
        title = None
    else:
        xlim = (3, 20) if xlim is None else xlim
        xlabel = 'Estimated N-AE (kg/kg)'
        title = 'Estimated N-AE for the\ndifferent estimators'
        
    if 'TIME' in estimator_name:
        if fertilizer == 'N':
            groups = ['Basal-Only', 'Top-Only', 'Basal+Single', 'Basal+Split']
        else:
            groups = ['Basal-Only', 'Top-Only']
    elif 'PFERT' in estimator_name:
        groups = ['DAP', 'N-Only', 'Other-NP']
    elif 'LEGUME' in estimator_name:
        groups = ['Legume', 'Non-legume']
    else:
        groups = [g for g in df['Group'].unique() if g != 'Overall']
    # Reverse groups so they plot top to bottom correctly as in standard error bars if needed,
    # or just keep them in order of appearance
    
    for soil in ['Non-sandy', 'Sandy']:
        tmp_soil_df = df[df['Soil type'] == soil].set_index('Group').reindex(groups)
        
        if tmp_soil_df.empty or tmp_soil_df['Mean Value'].isnull().all():
            continue
            
        y = np.arange(len(groups)) - (0.2 if soil == 'Non-sandy' else -0.2)
        
        if label == "_nolegend_":
            label_str = "_nolegend_"
        elif label is not None:
            # Only apply custom label once to prevent duplicate legend entries
            label_str = label if soil == 'Non-sandy' else "_nolegend_"
        else:
            label_str = soil
            
        if plot_ci:
            xerr = np.abs(tmp_soil_df[['CI Lower', 'CI Upper']].values.T - tmp_soil_df['Mean Value'].values)
            ax.errorbar(
                y=y, x=tmp_soil_df['Mean Value'], xerr=xerr,
                label=label_str, color=colors.get(soil, 'k'), **plot_kwargs
            )
        else:
            ax.plot(
                tmp_soil_df['Mean Value'], y,
                label=label_str, color=colors.get(soil, 'k'), **plot_kwargs
            )
        
        if 'Count' in tmp_soil_df.columns:
            for n, cluster in enumerate(groups):
                count_val = tmp_soil_df.loc[cluster, 'Count']
                if pd.notnull(count_val):
                    ax.text(
                        tmp_soil_df.loc[cluster, 'CI Upper'], y[n], 
                        f' ({int(count_val)}) ',
                        ha='left', va='center', fontsize=7
                    )
                    
    ax.set_yticks(np.arange(len(groups)))
    ax.set_yticklabels([f'{g:>15}' for g in groups])
    ax.set_xlabel(xlabel)
    
    if title:
        ax.set_title(title)
        
    ax.set_xlim(*xlim)
    
    if 'PFERT' in estimator_name:
        ax.set_ylim(-0.5, 2.5)
    else:
        ax.set_ylim(-0.5, len(groups) - 0.5)
        
    y_ticks = ax.get_yticks()
    ax.set_yticks(y_ticks - 0.5, minor=True)
    ax.grid(which='minor', axis='y', linestyle='-')
    ax.grid(which='major', axis='y', linewidth=0)
    
    if 'TIME' in estimator_name or 'LEGUME' in estimator_name or 'PFERT' in estimator_name:
        ax.axvline(0, color='k', linestyle='--')
    if save_path:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        plt.savefig(save_path, format='pdf', bbox_inches='tight', dpi=300)
        plt.close()
        print(f"Saved point estimates plot to {save_path}")

def plot_ucc_contours(ucc_data, save_path=None, levels=10, show_ci=True, critical_value=0.0, ax=None, title='UCC Sensitivity Contour'):
    """
    Plots the 2-D contour for the Unobserved Common Confounder (UCC) sensitivity analysis.
    """
    import numpy as np
    try:
        plt.style.use('publication.mplstyle')
    except Exception as e:
        pass
        
    if ax is None:
        fig, ax = plt.subplots(1, 1, figsize=(4, 3))
    else:
        fig = ax.figure
        
    grid_cd = ucc_data['grid_cd']
    grid_cy = ucc_data['grid_cy']
    adj_estimate = ucc_data['adj_estimate']
    ci_lower = ucc_data['ci_lower']
    benchmarks = ucc_data.get('benchmarks', None)
    
    # Plot filled contours for the adjusted estimate
    cf = ax.contourf(grid_cd, grid_cy, adj_estimate, levels=levels, cmap='RdBu', alpha=0.8)
    cbar = fig.colorbar(cf, ax=ax)
    cbar.set_label('Adjusted ATE')
    
    # Add contour lines
    ct = ax.contour(grid_cd, grid_cy, adj_estimate, levels=levels, colors='k', linewidths=0.5, alpha=0.5)
    ax.clabel(ct, inline=True, fontsize=8, fmt='%.1f')
    
    # Highlight the critical contour for point estimate
    # Find if it crosses the critical value
    if np.nanmin(adj_estimate) <= critical_value <= np.nanmax(adj_estimate):
        ax.contour(grid_cd, grid_cy, adj_estimate, levels=[critical_value], colors='red', linestyles='solid', linewidths=2)
        
    # Highlight the critical contour for the confidence interval
    if show_ci and np.nanmin(ci_lower) <= critical_value <= np.nanmax(ci_lower):
        # ax.contour(grid_cd, grid_cy, ci_lower, levels=[critical_value], colors='red', linestyles='dashed', linewidths=2)
        # Add a custom line to legend for the CI
        # import matplotlib.lines as mlines
        # ci_line = mlines.Line2D([], [], color='red', linestyle='dashed', linewidth=2, label=f'Lower CI = {critical_value}')
        
        handles, labels = ax.get_legend_handles_labels()
        # handles.append(ci_line)
        ax.legend(handles=handles, loc='upper right', frameon=True, fontsize=8)
    
    factor_dict = {
        'soil': 'S',
        'fertilizerAmountP': 'P',
        'fertilizerAmountN': 'N',
        # 'weatherSeason': 'W',
        'otherManagement': 'O',
        # 'variety': 'V',
        # 'investmentCap': 'I',
        # 'accessibilityRAI': 'A',
        'fieldHistory': 'H'
    }

    if benchmarks:
        for name, (cd, cy) in benchmarks.items():
            if cd == 0 and cy == 0:
                continue
            if name not in factor_dict:
                continue
            # ax.plot(cd, cy, 'k*', markersize=10, markeredgecolor='white')
            ax.annotate(factor_dict[name], (cd, cy), xytext=(5, 5), textcoords='offset points', fontsize=8,
                        bbox=dict(boxstyle='round,pad=0.2', fc='white', alpha=0.7, ec='none'))
            
    ax.set_xlabel(r'Treatment variance explained by UCC ($c_d$)')
    ax.set_ylabel(r'Outcome variance explained by UCC ($c_y$)')
    ax.set_title(title)
    
    if save_path:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        fig.savefig(save_path, format='pdf', bbox_inches='tight', dpi=300)
        plt.close(fig)
        print(f"Saved UCC contour plot to {save_path}")

